-- 코드를 입력하세요
SELECT DISTINCT USER_ID, PRODUCT_ID
FROM ONLINE_SALE A
WHERE EXISTS(
    SELECT 1
    FROM ONLINE_SALE B
    WHERE A.USER_ID = B.USER_ID
    AND A.PRODUCT_ID = B.PRODUCT_ID
    AND A.SALES_DATE <> B.SALES_DATE
)
ORDER BY USER_ID, PRODUCT_ID DESC