SELECT CRCC.CAR_ID, CRCC.CAR_TYPE, 
       FLOOR(CRCC.DAILY_FEE * (1 - (CAST(REPLACE(CRCDP.DISCOUNT_RATE, '%', '') AS UNSIGNED) / 100)) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CRCC
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP 
    ON CRCC.CAR_TYPE = CRCDP.CAR_TYPE AND CRCDP.DURATION_TYPE = '30일 이상'
LEFT JOIN (
    SELECT CAR_ID, 
           COUNT(CASE WHEN START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01' THEN 1 END) AS RENT_COUNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
    HAVING RENT_COUNT = 0
) CRCRH ON CRCC.CAR_ID = CRCRH.CAR_ID
WHERE CRCC.CAR_TYPE IN ('세단', 'SUV')
AND CRCRH.CAR_ID IS NOT NULL
AND FLOOR(CRCC.DAILY_FEE * (1 - (CAST(REPLACE(CRCDP.DISCOUNT_RATE, '%', '') AS UNSIGNED) / 100)) * 30) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CRCC.CAR_TYPE ASC, CRCC.CAR_ID DESC;