-- 코드를 입력하세요
SELECT F.FLAVOR
FROM FIRST_HALF F, ICECREAM_INFO I
WHERE F.FLAVOR IN(SELECT I.FLAVOR FROM ICECREAM_INFO WHERE I.INGREDIENT_TYPE = "fruit_based") AND F.TOTAL_ORDER>3000
ORDER BY F.TOTAL_ORDER DESC